// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Context;

namespace api.Migrations
{
    [DbContext(typeof(MovieInfoContext))]
    [Migration("20220104213755_SampleData")]
    partial class SampleData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("api.Entities.Cast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Character")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Casts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 50,
                            Character = "Andy Dufresne",
                            MovieId = 1,
                            Name = "Tim Robbins"
                        },
                        new
                        {
                            Id = 2,
                            Age = 50,
                            Character = "Andy Dufresne",
                            MovieId = 1,
                            Name = "Morgan Freeman"
                        },
                        new
                        {
                            Id = 3,
                            Age = 50,
                            Character = "Andy Dufresne",
                            MovieId = 1,
                            Name = "Bob Gunton"
                        },
                        new
                        {
                            Id = 4,
                            Age = 50,
                            Character = "Andy Dufresne",
                            MovieId = 2,
                            Name = "Bob Gunton"
                        },
                        new
                        {
                            Id = 5,
                            Age = 50,
                            Character = "Andy Dufresne",
                            MovieId = 3,
                            Name = "Bob Gunton"
                        },
                        new
                        {
                            Id = 6,
                            Age = 50,
                            Character = "Andy Dufresne",
                            MovieId = 4,
                            Name = "Bob Gunton"
                        },
                        new
                        {
                            Id = 7,
                            Age = 50,
                            Character = "Andy Dufresne",
                            MovieId = 5,
                            Name = "Bob Gunton"
                        },
                        new
                        {
                            Id = 8,
                            Age = 50,
                            Character = "Andy Dufresne",
                            MovieId = 1,
                            Name = "Bob Gunton"
                        },
                        new
                        {
                            Id = 9,
                            Age = 50,
                            Character = "Andy Dufresne",
                            MovieId = 2,
                            Name = "Bob Gunton"
                        },
                        new
                        {
                            Id = 10,
                            Age = 50,
                            Character = "Andy Dufresne",
                            MovieId = 3,
                            Name = "Bob Gunton"
                        },
                        new
                        {
                            Id = 11,
                            Age = 50,
                            Character = "Andy Dufresne",
                            MovieId = 4,
                            Name = "Bob Gunton"
                        },
                        new
                        {
                            Id = 12,
                            Age = 50,
                            Character = "Andy Dufresne",
                            MovieId = 5,
                            Name = "Bob Gunton"
                        },
                        new
                        {
                            Id = 13,
                            Age = 50,
                            Character = "Andy Dufresne",
                            MovieId = 1,
                            Name = "Bob Gunton"
                        },
                        new
                        {
                            Id = 14,
                            Age = 50,
                            Character = "Andy Dufresne",
                            MovieId = 2,
                            Name = "Bob Gunton"
                        },
                        new
                        {
                            Id = 15,
                            Age = 50,
                            Character = "Andy Dufresne",
                            MovieId = 3,
                            Name = "Bob Gunton"
                        });
                });

            modelBuilder.Entity("api.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Two imprisoned",
                            Name = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
                            Name = "The Godfather"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The early life and career of Vito Corleone in 1920s New York is portrayed while his son, Michael, expands and tightens his grip on his crime syndicate stretching from Lake Tahoe, Nevada to pre-revolution 1958 Cuba.",
                            Name = "The Godfather: Part II"
                        },
                        new
                        {
                            Id = 4,
                            Description = "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, the caped crusader must come to terms with one of the greatest psychological tests of his ability to fight injustice.",
                            Name = "The Dark Knight"
                        },
                        new
                        {
                            Id = 5,
                            Description = "A look at the relationship between the life of a young",
                            Name = "12 Angry"
                        });
                });

            modelBuilder.Entity("api.Entities.Cast", b =>
                {
                    b.HasOne("api.Entities.Movie", "Movie")
                        .WithMany("Cast")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("api.Entities.Movie", b =>
                {
                    b.Navigation("Cast");
                });
#pragma warning restore 612, 618
        }
    }
}
